wikipedia_base_url:
  default: en.wikipedia.org
  type: string
  description: theme_metadata.settings.wikipedia_base_url

wikipedia_preview_show_image:
  default: true
  type: bool
  description: theme_metadata.settings.wikipedia_preview_show_image

wikipedia_preview_use_extract_html:
  default: true
  type: bool
  description: theme_metadata.settings.wikipedia_preview_use_extract_html

wikipedia_preview_tooltip_placement:
  default: right
  type: enum
  choices:
    - right
    - left
    - top
    - bottom
  description: theme_metadata.settings.wikipedia_preview_tooltip_placement